### PR TITLE
fix empty intervals in svl parser

### LINKED ISSUE #2: Empty intervals in SPAM JAMS
Some of the SPAM data has duration-0 intervals.  I think this is coming from two places:
1. duplicate time markers in the svl file
2. time markers coinciding with track boundaries.

Here's a list of the offending annotations:

```
Cerulean_Leonard_Bernstein,_New_York_Philharmonic_&_Rudol.jams Eleni Vasilia Maltas segment_salami_upper
Cerulean_Miles_Davis_Quintet-Footprints.jams Eleni Vasilia Maltas segment_salami_lower
Isophonics_01 The Show Must Go On.jams Eleni Vasilia Maltas segment_salami_upper
Isophonics_05 Somebody To Love.jams Eleni Vasilia Maltas segment_salami_upper
Isophonics_CD1_-_14_-_Don't_Pass_Me_By.jams Evan S. Johnson segment_salami_upper
Isophonics_CD1_-_14_-_Don't_Pass_Me_By.jams Evan S. Johnson segment_salami_lower
SALAMI_1324.jams Eleni Vasilia Maltas segment_salami_lower
SALAMI_20.jams Eleni Vasilia Maltas segment_salami_lower
SALAMI_478.jams Eleni Vasilia Maltas segment_salami_upper
SALAMI_728.jams Eleni Vasilia Maltas segment_salami_lower
SALAMI_830.jams Eleni Vasilia Maltas segment_salami_upper
```

These are all pretty easily fixable.  For instance, the Miles track has the following annotation entries:

```
      <point frame="0" label="New Point" />
      <point frame="0" label="New Point" />
      <point frame="195120" label="a" />
```

which can be easily stripped out in the svl parser by calling `unique` on the boundary times before doing the interval conversion.

@urinieto Is it preferred to fix this within the svl files, or within the parser?

### PR DESCRIPTION
**Pull request by bmcfee**
This should fix #2.

It also fixes a potential problem that final boundaries may not be included in the parser.

The one question I have for @urinieto is how to run this script?  Am I supposed to call `svl2jams` directly, or does `parse_results` do everything for me?

### CODE REVIEW

**Comment by bmcfee** [comment]
[this looks like a mistake](https://github.com/urinieto/msaf-data/blob/master/SPAM/original_references/Eleni/SALAMI_830_s.svl#L5)

**Comment by bmcfee** [comment]
I think this is ready to go.

The multi-segment extraction notebook has been cleaned up a little, see the revised version [here](https://gist.github.com/ec40f7ae72238bc1c95bc2ba95a9f785).

**Comment by urinieto** [comment]
I believe `parse_results` shoould do everything for you. Thanks for doing this. Looking good!

**Comment by urinieto** [comment]
Just realized that this PR destroyed all the file metadata. We should automatize this, working on it.

**Pull request merged**
